-- MySQL Script generated by MySQL Workbench
-- Thu May 21 21:29:04 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `id_Productos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Costo` FLOAT NULL,
  `Stock` INT NULL,
  `Precio_venta` FLOAT NULL,
  PRIMARY KEY (`id_Productos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `id_Ventas` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NULL,
  `Descuento` FLOAT NULL,
  `Total` FLOAT NULL,
  `Monto_resivido` FLOAT NULL,
  PRIMARY KEY (`id_Ventas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalles_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalles_venta` (
  `id_Detalles` INT NOT NULL,
  `id_Ventas` INT NOT NULL,
  `id_Productos` INT NOT NULL,
  `Cantidad` INT NULL,
  `Precio_unitario` FLOAT NULL,
  `Subtotal` FLOAT NULL,
  PRIMARY KEY (`id_Detalles`),
  INDEX `fk_Detalles_venta_Ventas1_idx` (`id_Ventas` ASC),
  CONSTRAINT `fk_Detalles_venta_Productos1`
    FOREIGN KEY (`id_Detalles`)
    REFERENCES `mydb`.`Productos` (`id_Productos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Detalles_venta_Ventas1`
    FOREIGN KEY (`id_Ventas`)
    REFERENCES `mydb`.`Ventas` (`id_Ventas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Deudores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Deudores` (
  `id_Deudores` INT NOT NULL AUTO_INCREMENT,
  `id_Ventas` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Monto_pendiente` FLOAT NULL,
  PRIMARY KEY (`id_Deudores`),
  INDEX `fk_Deudores_Ventas1_idx` (`id_Ventas` ASC),
  CONSTRAINT `fk_Deudores_Ventas1`
    FOREIGN KEY (`id_Ventas`)
    REFERENCES `mydb`.`Ventas` (`id_Ventas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
