/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package negocio_mi.lupita;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SwingUtilities;



/**
 *
 * @author jesus-luis
 */
public class FrmInterfazDeudores extends javax.swing.JFrame {
        PreparedStatement ps;
        ResultSet rs;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmInterfazDeudores.class.getName());

    /**
     * Creates new form FrmInterfazVentas
     */
    public FrmInterfazDeudores() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
        mostrarfecha();
        mostrarVentas();

    }

    public void mostrarfecha() {
        Date d = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        LblFecha.setText(formato.format(d));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        Logo_Ventas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Boton_Guardar = new javax.swing.JButton();
        LblFecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFDeuda = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TFNumVenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TFDeudor = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Deudores = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TFDeleteDeudor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Boton_Eliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo_Ventas.setFont(new java.awt.Font("Liberation Sans", 2, 36)); // NOI18N
        Logo_Ventas.setText("Deudores");
        getContentPane().add(Logo_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 190, 40));

        jLabel1.setText("Fecha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setText("jesusdev@gmail.com");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 160, -1));

        Boton_Guardar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        Boton_Guardar.setText("Guardar deudor");
        Boton_Guardar.addActionListener(this::Boton_GuardarActionPerformed);
        getContentPane().add(Boton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 690, 270, 50));

        LblFecha.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        getContentPane().add(LblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 100, 20));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setText("Cantidad a dever");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        getContentPane().add(TFDeuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 120, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel8.setText("Detalles del deudor");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Numero de venta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        jPanel1.add(TFNumVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 120, -1));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel5.setText("Nombre del deudor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));
        jPanel1.add(TFDeudor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 700, 160));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        jLabel7.setText("Registro de deudores");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        Table_Deudores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table_Deudores);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 740, 320));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 780, 390));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel6.setText("Eliminar deudor");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        TFDeleteDeudor.setForeground(new java.awt.Color(204, 204, 204));
        TFDeleteDeudor.setText("Inserte id del deudor a liminar");
        TFDeleteDeudor.addActionListener(this::TFDeleteDeudorActionPerformed);
        jPanel3.add(TFDeleteDeudor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 220, -1));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel9.setText("Acciones");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Boton_Eliminar.setText("Eliminar");
        Boton_Eliminar.addActionListener(this::Boton_EliminarActionPerformed);
        jPanel3.add(Boton_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 140, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 400, 130));
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 850));

        jMenu1.setText("Ventas");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inventario");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu6.setText("Deudores");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        FrmInterfazVentas ventas = new FrmInterfazVentas();
        ventas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        FrmInterfazProductos productos = new FrmInterfazProductos();
        productos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        FrmInterfazDeudores deudores = new FrmInterfazDeudores();
        deudores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu6MouseClicked

    private void Boton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_GuardarActionPerformed
        Conexion_BD conect=new Conexion_BD();
        Connection con=conect.conectar();
        try {
            ps = con.prepareStatement("insert into Deudores(id_Ventas,Nombre,Monto_pendiente) values(?,?,?)");
            ps.setString(1, TFNumVenta.getText());
            ps.setString(2, TFDeudor.getText());
            ps.setString(3, TFDeuda.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deudor registrado con exito");
            limpiar();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());   //imprime exactamente donde fallo
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_Boton_GuardarActionPerformed

    private void Boton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_EliminarActionPerformed
        Conexion_BD conect=new Conexion_BD();
        Connection con=conect.conectar();
        try {
            ps = con.prepareStatement("delete from Productos where id_Deudores=?");
            ps.setInt(1, Integer.parseInt(TFDeleteDeudor.getText()));
            ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Producto eliminado con exito");
                limpiar();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());   //imprime exactamente donde fallo
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_Boton_EliminarActionPerformed

    private void TFDeleteDeudorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFDeleteDeudorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFDeleteDeudorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
        FrmInterfazDeudores frame = new FrmInterfazDeudores();
        SwingUtilities.updateComponentTreeUI(frame);  // ← AGREGA ESTO
        frame.setVisible(true);
    });
    }
    
    public void limpiar(){
    TFNumVenta.setText(" ");
    TFDeudor.setText(" ");
    TFDeuda.setText(" ");
    }
    
    public DefaultTableModel mostrarVentas(){
        String[] nombreColumnas={"id_Deudores","id_Ventas","Nombre","Monto_pendiente"};
        String[] registros=new String[4];
        DefaultTableModel modelo=new DefaultTableModel(null,nombreColumnas);
        ps=null;
        rs=null;
        try {
            Conexion_BD conect=new Conexion_BD();
            Connection con=conect.conectar();
            ps = con.prepareStatement("select * from Deudores");
            rs=ps.executeQuery();
            while(rs.next()){
            registros[0]=rs.getString("id_Deudores");
            registros[1]=rs.getString("id_Ventas");
            registros[2]=rs.getString("Nombre");
            registros[3]=rs.getString("Monto_pendiente");
            modelo.addRow(registros);
            Table_Deudores.setModel(modelo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());   //imprime exactamente donde fallo
            System.out.println(e.getMessage());
        }return modelo;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Eliminar;
    private javax.swing.JButton Boton_Guardar;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JLabel Logo_Ventas;
    private javax.swing.JTextField TFDeleteDeudor;
    private javax.swing.JTextField TFDeuda;
    private javax.swing.JTextField TFDeudor;
    private javax.swing.JTextField TFNumVenta;
    private javax.swing.JTable Table_Deudores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
