/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package negocio_mi.lupita;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Statement;
import javax.swing.SwingUtilities;

/**
 *
 * @author jesus-luis
 */
public class FrmInterfazVentas extends javax.swing.JFrame {
        PreparedStatement ps;
        PreparedStatement ps1;
        PreparedStatement ps2;
        ResultSet rs;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmInterfazVentas.class.getName());

    /**
     * Creates new form FrmInterfazVentas
     */
    public FrmInterfazVentas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
        mostrarfecha();
        mostrarVentas();
        mostrarTotal();
        mostrarSubtotal();
    }

    public void mostrarfecha() {
        Date d = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        LblFecha.setText(formato.format(d));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        Logo_Ventas = new javax.swing.JLabel();
        LblFecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Boton_Guardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TFPrecioProducto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TFMontoResivido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SpinnerProducto = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        TFCantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TFDescuento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TFFecha_venta = new javax.swing.JTextField();
        TFTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Ventas = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        TFId_ventas = new javax.swing.JTextField();
        Boton_Eliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TFSubtotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo_Ventas.setFont(new java.awt.Font("Liberation Sans", 2, 36)); // NOI18N
        Logo_Ventas.setText("Ventas");
        getContentPane().add(Logo_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 130, 40));

        LblFecha.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        LblFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario.png"))); // NOI18N
        getContentPane().add(LblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 150, 20));

        jLabel1.setText("Fecha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setText("jesusdev@gmail.com");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 170, -1));

        Boton_Guardar.setBackground(new java.awt.Color(115, 148, 226));
        Boton_Guardar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Boton_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disco-flexible.png"))); // NOI18N
        Boton_Guardar.setText("  Guardar venta");
        Boton_Guardar.addActionListener(this::Boton_GuardarActionPerformed);
        getContentPane().add(Boton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 710, 270, 60));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel3.setText("Total :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 660, -1, -1));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        jLabel10.setText("Reporte de ventas");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Precio del producto");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        jPanel1.add(TFPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 110, -1));

        jLabel8.setText("Monto resivido");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));
        jPanel1.add(TFMontoResivido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 100, -1));

        jLabel4.setText("Id_Producto");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));
        jPanel1.add(SpinnerProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 110, -1));

        jLabel5.setText("Cantidad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));
        jPanel1.add(TFCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 100, -1));

        jLabel6.setText("Descuento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));
        jPanel1.add(TFDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 100, -1));

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel13.setText("Detalles del producto");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel11.setText("Fehca de venta");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));
        jPanel1.add(TFFecha_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 750, 140));

        TFTotal.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        getContentPane().add(TFTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table_Ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table_Ventas);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 740, 320));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 790, 400));

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel14.setText("Acciones");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Insertar ID a eliminar");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel3.add(TFId_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 30));

        Boton_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        Boton_Eliminar.setText("  Eliminar");
        Boton_Eliminar.addActionListener(this::Boton_EliminarActionPerformed);
        jPanel3.add(Boton_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 130, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 340, 120));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel9.setText("Subtotal :");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        TFSubtotal.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        TFSubtotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ahorrar-dinero.png"))); // NOI18N
        jPanel5.add(TFSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 60));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 650, 450, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avatar.png"))); // NOI18N
        jLabel2.setText("Usuario");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 810));

        jMenuBar1.setBorder(null);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bienes.png"))); // NOI18N
        jMenu1.setText("Ventas");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventario-disponible.png"))); // NOI18N
        jMenu2.setText("Inventario");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avatar.png"))); // NOI18N
        jMenu6.setText("Deudores");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        FrmInterfazVentas ventas = new FrmInterfazVentas();
        ventas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        FrmInterfazProductos productos = new FrmInterfazProductos();
        productos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        FrmInterfazDeudores deudores = new FrmInterfazDeudores();
        deudores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu6MouseClicked

    private void Boton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_GuardarActionPerformed
        try {
            Conexion_BD conect = new Conexion_BD();
            Connection con = conect.conectar();

            // Inicia transacción
            con.setAutoCommit(false);

            // 1INSERT en Ventas
            ps = con.prepareStatement(
                "INSERT INTO Ventas(Fecha, Descuento, Monto_resivido) VALUES(?, ?, ?)",
                Statement.RETURN_GENERATED_KEYS  // ← Obtiene el ID generado
            );
            ps.setString(1, TFFecha_venta.getText());
            ps.setDouble(2, Double.parseDouble(TFDescuento.getText()));
            ps.setDouble(3, Double.parseDouble(TFMontoResivido.getText()));
            ps.executeUpdate();

            // 2️Obtener el ID de la venta insertada
            rs = ps.getGeneratedKeys();
            int idVenta = 0;
            if (rs.next()) {
                idVenta = rs.getInt(1);
            }
            
            // 3 DEBUG: Ver qué ID de producto está intentando insertar
            int idProducto = (Integer) SpinnerProducto.getValue();
            System.out.println("ID Producto del Spinner: " + idProducto);
            
            double precioUnitario = Double.parseDouble(TFPrecioProducto.getText());
            int cantidad = Integer.parseInt(TFCantidad.getText());

            // Calcular el subtotal
            double subtotal = precioUnitario * cantidad;
            // 3️INSERT en Detalles_venta CON el ID de venta
            ps1 = con.prepareStatement(
                "INSERT INTO Detalles_venta(id_Ventas, id_Productos, Cantidad, Precio_unitario, Subtotal) VALUES(?, ?, ?, ?, ?)"
            );
            ps1.setInt(1, idVenta);  // ← ID de la venta recién insertada
            ps1.setInt(2, (Integer) SpinnerProducto.getValue()); // ← Del spinner
            ps1.setInt(3, Integer.parseInt(TFCantidad.getText()));
            ps1.setDouble(4, Double.parseDouble(TFPrecioProducto.getText()));
            ps1.setDouble(5, subtotal);  // ← Subtotal calculado
            ps1.executeUpdate();

            // 4️Restar del stock
            ps2 = con.prepareStatement(
                "UPDATE Productos SET Stock = Stock - ? WHERE id_Productos = ?"
            );
            ps2.setInt(1, Integer.parseInt(TFCantidad.getText())); // Cantidad vendida
            ps2.setInt(2, idProducto);
            ps2.executeUpdate();

            // 4️Confirma todo
            con.commit();
            JOptionPane.showMessageDialog(null, "Venta registrada correctamente");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_Boton_GuardarActionPerformed

    private void Boton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_EliminarActionPerformed
        Conexion_BD conect=new Conexion_BD();
        Connection con=conect.conectar();
        try {
            ps = con.prepareStatement("delete from Ventas where id_ventas=?");
            ps.setInt(1, Integer.parseInt(TFId_ventas.getText()));
            int res = ps.executeUpdate();
            if (res>0) {
                JOptionPane.showMessageDialog(null, "Venta eliminada con exito");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Venta no eliminada");
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_Boton_EliminarActionPerformed

    public void mostrarSubtotal()
{
    Conexion_BD conect = new Conexion_BD();
    Connection con = conect.conectar();
    PreparedStatement ps1 = null;  // ← Nueva variable
    PreparedStatement ps2 = null;  // ← Nueva variable
    ResultSet rs1 = null;
    ResultSet rs2 = null;

    try {
        // 1️⃣ Obtener el último ID de venta
        String sqlMaxId = "SELECT MAX(id_Ventas) as id_Ventas FROM Ventas";
        ps1 = con.prepareStatement(sqlMaxId);
        rs1 = ps1.executeQuery();
        
        int idVenta = 0;
        if (rs1.next()) {
            idVenta = rs1.getInt("id_Ventas");
        }
        
        if (idVenta == 0) {
            TFSubtotal.setText("0.00");
            return;
        }
        
        // 2️⃣ Obtener el subtotal
        String sql = "SELECT SUM(Subtotal) as Subtotal FROM Detalles_venta WHERE id_Ventas = ?";
        ps2 = con.prepareStatement(sql);
        ps2.setInt(1, idVenta);  // ← Ahora es ps2
        rs2 = ps2.executeQuery();
        
        if (rs2.next()) {
            double subtotal = rs2.getDouble("Subtotal");
            TFSubtotal.setText(String.format("%.2f", subtotal));
            System.out.println("Subtotal: " + subtotal);
        }
        
        rs1.close();
        rs2.close();
        ps1.close();
        ps2.close();
        con.close();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        System.out.println("Error: " + e.getMessage());
        e.printStackTrace();
    }
}
    
    public void mostrarTotal()
    {
        Conexion_BD conect = new Conexion_BD();
        Connection con = conect.conectar();
    
    try {
        // Primero obtener el último id_venta registrado
        String sqlMaxId = "SELECT MAX(id_Ventas) as id_Ventas FROM Ventas";
        ps = con.prepareStatement(sqlMaxId);
        rs = ps.executeQuery();
        
        int idVenta = 0;
        if (rs.next()) {
            idVenta = rs.getInt("id_Ventas");
        }
        
        // Luego calcular el total con ese id_venta
        String sql = "SELECT SUM(dv.Subtotal * (1 - v.Descuento/100)) as total FROM Detalles_venta dv INNER JOIN Ventas v ON dv.id_Ventas = v.id_Ventas WHERE dv.id_Ventas = ?";
        ps = con.prepareStatement(sql);
        ps.setInt(1, idVenta);
        rs = ps.executeQuery();
        
        if (rs.next()) {
            double total = rs.getDouble("total");
            TFTotal.setText(String.format("%.2f", total));
        }
        
        
        rs.close();
        ps.close();
        con.close();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
        FrmInterfazVentas frame = new FrmInterfazVentas();
        SwingUtilities.updateComponentTreeUI(frame);  // ← AGREGA ESTO
        frame.setVisible(true);
    });
    }
    
    public void limpiar(){
        TFFecha_venta.setText("");
        TFDescuento.setText("");
        TFTotal.setText(" ");
        TFMontoResivido.setText("");
        SpinnerProducto.setValue("");
        TFCantidad.setText("");
        TFPrecioProducto.setText("");
        TFSubtotal.setText("");
        TFTotal.setText(" ");
    }
    
    public DefaultTableModel mostrarVentas(){
        String[] nombreColumnas={"id_Ventas","Nombre","Cantidad","Subtotal","Descuento"};
        String[] registros=new String[5];
        DefaultTableModel modelo=new DefaultTableModel(null,nombreColumnas);
        ps=null;
        rs=null;
        try {
            Conexion_BD conect=new Conexion_BD();
            Connection con=conect.conectar();
            ps = con.prepareStatement("SELECT v.id_Ventas, p.Nombre, dv.Cantidad, dv.Subtotal, v.Descuento FROM Ventas v INNER JOIN Detalles_venta dv ON v.id_Ventas = dv.id_Ventas INNER JOIN Productos p ON dv.id_Productos = p.id_Productos;");
            rs=ps.executeQuery();
            while(rs.next()){
            registros[0]=rs.getString("id_Ventas");
            registros[1]=rs.getString("Nombre");
            registros[2]=rs.getString("Cantidad");
            registros[3]=rs.getString("Subtotal");
            registros[4]=rs.getString("Descuento");
            modelo.addRow(registros);
            Table_Ventas.setModel(modelo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al conectar");
        }return modelo;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Eliminar;
    private javax.swing.JButton Boton_Guardar;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JLabel Logo_Ventas;
    private javax.swing.JSpinner SpinnerProducto;
    private javax.swing.JTextField TFCantidad;
    private javax.swing.JTextField TFDescuento;
    private javax.swing.JTextField TFFecha_venta;
    private javax.swing.JTextField TFId_ventas;
    private javax.swing.JTextField TFMontoResivido;
    private javax.swing.JTextField TFPrecioProducto;
    private javax.swing.JLabel TFSubtotal;
    private javax.swing.JLabel TFTotal;
    private javax.swing.JTable Table_Ventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
