/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package negocio_mi.lupita;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Statement;

/**
 *
 * @author jesus-luis
 */
public class FrmInterfazVentas extends javax.swing.JFrame {
        PreparedStatement ps;
        PreparedStatement ps1;
        ResultSet rs;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmInterfazVentas.class.getName());

    /**
     * Creates new form FrmInterfazVentas
     */
    public FrmInterfazVentas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
        mostrarfecha();

    }

    public void mostrarfecha() {
        Date d = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        LblFecha.setText(formato.format(d));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        Logo_Ventas = new javax.swing.JLabel();
        LblFecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Ventas = new javax.swing.JTable();
        Boton_Guardar = new javax.swing.JButton();
        Boton_Eliminar = new javax.swing.JButton();
        TFTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TFProducto = new javax.swing.JTextField();
        TFPrecioProducto = new javax.swing.JTextField();
        TFCantidad = new javax.swing.JTextField();
        TFMontoResivido = new javax.swing.JTextField();
        TFDescuento = new javax.swing.JTextField();
        TFSubtotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TFFecha_venta = new javax.swing.JTextField();
        TFId_ventas = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 233, 187));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo_Ventas.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        Logo_Ventas.setText("Ventas");
        getContentPane().add(Logo_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 80, 40));

        LblFecha.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        getContentPane().add(LblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 90, 20));

        jLabel1.setText("Fecha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setText("jesusdev@gmail.com");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 120, -1));

        Table_Ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Subtotal", "Descuento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table_Ventas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 740, 320));

        Boton_Guardar.setText("Guardar");
        Boton_Guardar.addActionListener(this::Boton_GuardarActionPerformed);
        getContentPane().add(Boton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 130, 50));

        Boton_Eliminar.setText("Eliminar");
        Boton_Eliminar.addActionListener(this::Boton_EliminarActionPerformed);
        getContentPane().add(Boton_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, 120, 50));

        TFTotal.setEditable(false);
        TFTotal.addActionListener(this::TFTotalActionPerformed);
        getContentPane().add(TFTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 200, 70));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel3.setText("Total :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, -1, -1));

        jLabel4.setText("Producto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel5.setText("Cantidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jLabel6.setText("Descuento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jLabel7.setText("Precio del producto");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel8.setText("Monto resivido");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabel9.setText("Subtotal");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));
        getContentPane().add(TFProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 100, -1));
        getContentPane().add(TFPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 100, -1));
        getContentPane().add(TFCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 100, -1));
        getContentPane().add(TFMontoResivido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 100, -1));
        getContentPane().add(TFDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 100, -1));
        getContentPane().add(TFSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 100, -1));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        jLabel10.setText("Reporte de ventas");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jLabel11.setText("Fehca de venta");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, -1));
        getContentPane().add(TFFecha_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 100, -1));
        getContentPane().add(TFId_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 120, -1));

        jLabel12.setText("Insertar id de venta a eliminar");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        jMenu1.setText("Ventas");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inventario");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu6.setText("Deudores");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        FrmInterfazVentas ventas = new FrmInterfazVentas();
        ventas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        FrmInterfazProductos productos = new FrmInterfazProductos();
        productos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        FrmInterfazDeudores deudores = new FrmInterfazDeudores();
        deudores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu6MouseClicked

    private void Boton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_GuardarActionPerformed
        try {
            Conexion_BD conect = new Conexion_BD();
            Connection con = conect.conectar();

            // Inicia transacción
            con.setAutoCommit(false);

            // 1INSERT en Ventas
            ps = con.prepareStatement(
                "INSERT INTO Ventas(Fecha, Descuento, Monto_resivido) VALUES(?, ?, ?)",
                Statement.RETURN_GENERATED_KEYS  // ← Obtiene el ID generado
            );
            ps.setString(1, TFFecha_venta.getText());
            ps.setDouble(2, Double.parseDouble(TFDescuento.getText()));
            ps.setDouble(3, Double.parseDouble(TFMontoResivido.getText()));
            ps.executeUpdate();

            // 2️Obtener el ID de la venta insertada
            rs = ps.getGeneratedKeys();
            int idVenta = 0;
            if (rs.next()) {
                idVenta = rs.getInt(1);
            }

            // 3️INSERT en Detalles_venta CON el ID de venta
            ps1 = con.prepareStatement(
                "INSERT INTO Detalles_venta(id_Ventas, id_Productos, Cantidad, Precio_unitario, Subtotal) VALUES(?, ?, ?, ?, ?)"
            );
            ps1.setInt(1, idVenta);  // ← ID de la venta recién insertada
            ps1.setInt(2, Integer.parseInt(TFProducto.getText()));
            ps1.setInt(3, Integer.parseInt(TFCantidad.getText()));
            ps1.setDouble(4, Double.parseDouble(TFPrecioProducto.getText()));
            ps1.setDouble(5, Double.parseDouble(TFSubtotal.getText()));
            ps1.executeUpdate();

            // 4️Confirma todo
            con.commit();
            JOptionPane.showMessageDialog(null, "Venta registrada correctamente");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_Boton_GuardarActionPerformed

    private void Boton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_EliminarActionPerformed
        Conexion_BD conect=new Conexion_BD();
        Connection con=conect.conectar();
        try {
            ps = con.prepareStatement("delete from Ventas where id_ventas=?");
            ps.setInt(1, Integer.parseInt(TFId_ventas.getText()));
            int res = ps.executeUpdate();
            if (res>0) {
                JOptionPane.showMessageDialog(null, "Venta eliminada con exito");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Venta no eliminada");
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_Boton_EliminarActionPerformed

    private void TFTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTotalActionPerformed
    Conexion_BD conect = new Conexion_BD();
    Connection con = conect.conectar();
    
    try {
        // Primero obtener el último id_venta registrado
        String sqlMaxId = "SELECT MAX(id_venta) as id_venta FROM Ventas";
        ps = con.prepareStatement(sqlMaxId);
        rs = ps.executeQuery();
        
        int idVenta = 0;
        if (rs.next()) {
            idVenta = rs.getInt("id_venta");
        }
        
        // Luego calcular el total con ese id_venta
        String sql = "SELECT SUM(dv.Subtotal * (1 - dv.Descuento/100)) as total " +
                     "FROM Detalle_Ventas dv " +
                     "WHERE dv.id_venta = ?";
        
        ps = con.prepareStatement(sql);
        ps.setInt(1, idVenta);
        rs = ps.executeQuery();
        
        if (rs.next()) {
            double total = rs.getDouble("total");
            TFTotal.setText(String.format("%.2f", total));
        }
        
        rs.close();
        ps.close();
        con.close();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_TFTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmInterfazVentas().setVisible(true));
    }
    
    public void limpiar(){
        TFFecha_venta.setText("");
        TFDescuento.setText("");
        TFTotal.setText(" ");
        TFMontoResivido.setText("");
        TFProducto.setText("");
        TFCantidad.setText("");
        TFPrecioProducto.setText("");
        TFSubtotal.setText("");
    }
    
    public DefaultTableModel mostrarVentas(){
        String[] nombreColumnas={"Producto","Cantidad","Subtotal","Descuento"};
        String[] registros=new String[3];
        DefaultTableModel modelo=new DefaultTableModel(null,nombreColumnas);
        PreparedStatement ps=null;
        ResultSet rs=null;
        try {
            Conexion_BD conect=new Conexion_BD();
            Connection con=conect.conectar();
            ps = con.prepareStatement("SELECT v.id_venta, p.Producto, dv.Cantidad, dv.Subtotal, dv.Descuento FROM Ventas v INNER JOIN Detalle_Ventas dv ON v.id_venta = dv.id_venta INNER JOIN Productos p ON dv.id_producto = p.id_producto;");
            rs=ps.executeQuery();
            while(rs.next()){
            registros[0]=rs.getString("id_venta");
            registros[0]=rs.getString("Producto");
            registros[1]=rs.getString("Cantidad");
            registros[2]=rs.getString("Subtotal");
            registros[3]=rs.getString("Descuento");
            modelo.addRow(registros);
            Table_Ventas.setModel(modelo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al conectar");
        }return modelo;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Eliminar;
    private javax.swing.JButton Boton_Guardar;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JLabel Logo_Ventas;
    private javax.swing.JTextField TFCantidad;
    private javax.swing.JTextField TFDescuento;
    private javax.swing.JTextField TFFecha_venta;
    private javax.swing.JTextField TFId_ventas;
    private javax.swing.JTextField TFMontoResivido;
    private javax.swing.JTextField TFPrecioProducto;
    private javax.swing.JTextField TFProducto;
    private javax.swing.JTextField TFSubtotal;
    private javax.swing.JTextField TFTotal;
    private javax.swing.JTable Table_Ventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
