/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package negocio_mi.lupita;
import javax.swing.SwingUtilities;

/**
 *
 * @author jesus-luis
 */
public class FrmLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Imagen = new javax.swing.JLabel();
        TFUsuario = new javax.swing.JTextField();
        TFContraseña = new javax.swing.JPasswordField();
        Boton_Entrada = new javax.swing.JButton();
        TFError = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user_icon_120x120.png"))); // NOI18N
        getContentPane().add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        TFUsuario.setBackground(new java.awt.Color(204, 204, 255));
        TFUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(TFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 250, 50));

        TFContraseña.setBackground(new java.awt.Color(204, 204, 255));
        TFContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFContraseñaKeyPressed(evt);
            }
        });
        getContentPane().add(TFContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 250, 50));

        Boton_Entrada.setText("Entrada");
        Boton_Entrada.addActionListener(this::Boton_EntradaActionPerformed);
        getContentPane().add(Boton_Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 120, 40));

        TFError.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TFError, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 150, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/simple-background-wallpaper-preview.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_EntradaActionPerformed
    // Verificasion de usuario por medio de sus datos
        FrmInterfazVentas ventas=new FrmInterfazVentas();
        if (TFUsuario.getText().equals("goloza69@hotmail.com")&&TFContraseña.getText().equals("123"))
        {
    // Cambio de ventanas
        ventas.setVisible(true);
        this.dispose();
        }
        else
        {
            TFError.setText("Error al iniciar sesion");
        }
    }//GEN-LAST:event_Boton_EntradaActionPerformed

    private void TFUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFUsuarioKeyPressed
    //Funcion para introducir datos sin usar el boton
        if(evt.getKeyCode()== java.awt.event.KeyEvent.VK_ENTER)
            Boton_Entrada.doClick();
    }//GEN-LAST:event_TFUsuarioKeyPressed

    private void TFContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFContraseñaKeyPressed
    //Funcion para introducir datos sin usar el boton
        if(evt.getKeyCode()== java.awt.event.KeyEvent.VK_ENTER)
            Boton_Entrada.doClick();
    }//GEN-LAST:event_TFContraseñaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
        FrmLogin frame = new FrmLogin();
        SwingUtilities.updateComponentTreeUI(frame);  // ← AGREGA ESTO
        frame.setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Entrada;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Imagen;
    private javax.swing.JPasswordField TFContraseña;
    private javax.swing.JLabel TFError;
    private javax.swing.JTextField TFUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
