/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package negocio_mi.lupita;

/**
 *
 * @author jesus-luis
 */
public class FrmLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagen = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        TFContraseña = new javax.swing.JPasswordField();
        BotonAcceso = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user_icon_120x120.png"))); // NOI18N
        getContentPane().add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        TFNombre.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(TFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 240, 50));

        TFContraseña.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(TFContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 240, 50));

        BotonAcceso.setText("Entar");
        BotonAcceso.addActionListener(this::BotonAccesoActionPerformed);
        getContentPane().add(BotonAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 140, 50));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/simple-background-wallpaper-preview.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAccesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAccesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton BotonAcceso;
    private javax.swing.JLabel Imagen;
    private javax.swing.JPasswordField TFContraseña;
    private javax.swing.JTextField TFNombre;
    // End of variables declaration//GEN-END:variables
}
